/**
 * Inducements for Blood Bowl teams
 */

export enum Inducement {
  TEMP_AGENCY_CHEERLEADER = "Temp Agency Cheerleader",
  PART_TIME_ASSISTANT_COACH = "Part-time Assistant Coach",
  WEATHER_MAGE = "Weather Mage",
  BLITZERS_BEST_KEGS = "Blitzer's Best Kegs",
  SPECIAL_PLAY = "Special Play",
  EXTRA_TEAM_TRAINING = "Extra Team Training",
  BRIBE = "Bribe",
  WANDERING_APOTHECARY = "Wandering Apothecary",
  MORTUARY_ASSISTANT = "Mortuary Assistant",
  PLAGUE_DOCTOR = "Plague Doctor",
  RIOTOUS_ROOKIES = "Riotous Rookies",
  HALFLING_MASTER_CHEF = "Halfling Master Chef",
  MERCENARY_PLAYER = "Mercenary Player",
  JOSEF_BUGMAN = "Infamous Coaching Staff: Josef Bugman",
  KARI_COLDSTEEL = "(In)Famous Coaching Staff: Kari Coldsteel",
  PAPA_SKULLBONES = "(In)Famous Coaching Staff: Papa Skullbones",
  GLANDRIL_SILVERWATER = "(In)Famous Coaching Staff: Glandril Silverwater",
  KROT_SHOCKWHISKER = "(In)Famous Coaching Staff: Krot Shockwhisker",
  AYLEEN_ANDAR = "(In)Famous Coaching Staff: Ayleen Andar",
  PROFESSOR_FRONKELHEIM = "(In)Famous Coaching Staff: Professor Frönkelheim",
  MUNGO_SPINECRACKER = "(In)Famous Coaching Staff: Mungo Spinecracker",
  FINK_DA_FIXER = "(In)Famous Coaching Staff: Fink Da Fixer",
  SCHIELUND_SCHARLITAN = "(In)Famous Coaching Staff: Schielund Scharlitan",
  WIZARD_SPORTS_WIZARD = "Wizard: Sports-Wizard",
  WIZARD_CHAOS_SORCERER = "Wizard: Chaos Sorcerer",
  WIZARD_DRUCHII_SORCERESS = "Wizard: Druchii Sorceress",
  WIZARD_ASUR_HIGH_MAGE = "Wizard: Asur High Mage",
  WIZARD_SLANN_MAGE_PRIEST = "Wizard: Slann Mage Priest",
  WIZARD_HORTICULTURALIST_OF_NURGLE = "Wizard: Horticulturalist of Nurgle",
  WIZARD_SPORTS_NECROTHEURGE = "Wizard: Sports Necrotheurge",
  WIZARD_WICKED_WITCH = "Wizard: Wicked Witch",
  WIZARD_WARLOCK_ENGINEER = "Wizard: Warlock Engineer",
  WIZARD_OGRE_FIREBELLY = "Wizard: Ogre Firebelly",
  WIZARD_NIGHT_GOBLIN_SHAMAN = "Wizard: Night Goblin Shaman",
  WIZARD_HORATIO_X_SCHOTTENHEIM = "Named Wizard: Horatio X. Schottenheim",
  BIASED_REFEREE = "Biased Referee",
  BIASED_REFEREE_RANULF_RED_HOKULI = "Biased Referee: Ranulf 'Red' Hokuli",
  BIASED_REFEREE_THORON_KORENSSON = "Biased Referee: Thoron Korensson",
  BIASED_REFEREE_JORM_THE_OGRE = "Biased Referee: Jorm the Ogre",
  BIASED_REFEREE_TRUNDLEFOOT_TRIPLETS = "Biased Referee: The Trundlefoot Triplets",
  WAAAGH_DRUMMER = "WAAAGH! Drummer",
  CAVORTING_NURGLING = "Cavorting Nurgling",
  DWARFEN_RUNESMITH = "Dwarfen Runesmith",
  HALFLING_HOT_POT = "Halfling Hot Pot",
  MASTER_OF_BALLISTICS = "Master of Ballistics",
  BOTTLES_OF_HEADY_BREW = "Bottles of Heady Brew",
  TEAM_MASCOT = "Team Mascot",
  MEDICAL_UNGUENT = "Medical Unguent",
  DESPERATE_MEASURES = "Desperate Measures",
  COLLEGE_WIZARD = "College Wizard",
  GIANT_MERCENARY_PLAYER = "Giant Mercenary Player",
  LESSER_MAGIC_POTION = "Lesser Magic Potion",
  SUPERIOR_MAGIC_POTION = "Superior Magic Potion",
  SAWBONES = "Sawbones",
  SNACK_STAND = "Snack Stand",
  NOVICE_WIZARD = "Novice Wizard",
  PRAYERS_TO_NUFFLE = "Prayers to Nuffle",
}
